[package]
name = "taikai"
version = "0.1.0"
authors = ["Manuel Schölling <manuel.schoelling@gmx.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "*"
proc-macro2 = "*"
syn = "*"
heck = "*"

[dev-dependencies]
nom = "*"
